#include <string>

#include <leonhard/problems_descriptions.hpp>

using namespace std;

using namespace leonhard;

const string &
problems_descriptions::describe(unsigned int number)
{
    static problems_descriptions instance;
    const_iterator it = instance.find(number);
    if (it == instance.end())
        return instance.invalid;
    return it->second;
}

problems_descriptions::problems_descriptions()
    : map<unsigned int, string>({
            { 1,   "Multiples of 3 and 5" },
            { 2,   "Even Fibonacci numbers" },
            { 3,   "Largest prime factor" },
            { 4,   "Largest palindrome product" },
            { 5,   "Smallest multiple" },
            { 6,   "Sum square difference" },
            { 7,   "10001st prime" },
            { 8,   "Largest product in a series" },
            { 9,   "Special Pythagorean triplet" },
            { 10,  "Summation of primes" },
            { 11,  "Largest product in a grid" },
            { 12,  "Highly divisible triangular number" },
            { 13,  "Large sum" },
            { 14,  "Longest Collatz sequence" },
            { 15,  "Lattice paths" },
            { 16,  "Power digit sum" },
            { 17,  "Number letter counts" },
            { 18,  "Maximum path sum I" },
            { 19,  "Counting Sundays" },
            { 20,  "Factorial digit sum" },
            { 21,  "Amicable numbers" },
            { 22,  "Names scores" },
            { 23,  "Non-abundant sums" },
            { 24,  "Lexicographic permutations" },
            { 25,  "1000-digit Fibonacci number" },
            { 26,  "Reciprocal cycles" },
            { 27,  "Quadratic primes" },
            { 28,  "Number spiral diagonals" },
            { 29,  "Distinct powers" },
            { 30,  "Digit fifth powers" },
            { 31,  "Coin sums" },
            { 32,  "Pandigital products" },
            { 33,  "Digit cancelling fractions" },
            { 34,  "Digit factorials" },
            { 35,  "Circular primes" },
            { 36,  "Double-base palindromes" },
            { 37,  "Truncatable primes" },
            { 38,  "Pandigital multiples" },
            { 39,  "Integer right triangles" },
            { 40,  "Champernowne's constant" },
            { 41,  "Pandigital prime" },
            { 42,  "Coded triangle numbers" },
            { 43,  "Sub-string divisibility" },
            { 44,  "Pentagon numbers" },
            { 45,  "Triangular, pentagonal, and hexagonal" },
            { 46,  "Goldbach's other conjecture" },
            { 47,  "Distinct primes factors" },
            { 48,  "Self powers" },
            { 49,  "Prime permutations" },
            { 50,  "Consecutive prime sum" },
            { 51,  "Prime digit replacements" },
            { 52,  "Permuted multiples" },
            { 53,  "Combinatoric selections" },
            { 54,  "Poker hands" },
            { 55,  "Lychrel numbers" },
            { 56,  "Powerful digit sum" },
            { 57,  "Square root convergents" },
            { 58,  "Spiral primes" },
            { 59,  "XOR decryption" },
            { 60,  "Prime pair sets" },
            { 61,  "Cyclical figurate numbers" },
            { 62,  "Cubic permutations" },
            { 63,  "Powerful digit counts" },
            { 64,  "Odd period square roots" },
            { 65,  "Convergents of e" },
            { 66,  "Diophantine equation" },
            { 67,  "Maximum path sum II" },
            { 68,  "Magic 5-gon ring" },
            { 69,  "Totient maximum" },
            { 70,  "Totient permutation" },
            { 71,  "Ordered fractions" },
            { 72,  "Counting fractions" },
            { 73,  "Counting fractions in a range" },
            { 74,  "Digit factorial chains" },
            { 75,  "Singular integer right triangles" },
            { 76,  "Counting summations" },
            { 77,  "Prime summations" },
            { 78,  "Coin partitions" },
            { 79,  "Passcode derivation" },
            { 80,  "Square root digital expansion" },
            { 81,  "Path sum: two ways" },
            { 82,  "Path sum: three ways" },
            { 83,  "Path sum: four ways" },
            { 84,  "Monopoly odds" },
            { 85,  "Counting rectangles" },
            { 86,  "Cuboid route" },
            { 87,  "Prime power triples" },
            { 88,  "Product-sum numbers" },
            { 89,  "Roman numerals" },
            { 90,  "Cube digit pairs" },
            { 91,  "Right triangles with integer coordinates" },
            { 92,  "Square digit chains" },
            { 93,  "Arithmetic expressions" },
            { 94,  "Almost equilateral triangles" },
            { 95,  "Amicable chains" },
            { 96,  "Su Doku" },
            { 97,  "Large non-Mersenne prime" },
            { 98,  "Anagramic squares" },
            { 99,  "Largest exponential" },
            { 100, "Arranged probability" },
            { 101, "Optimum polynomial" },
            { 102, "Triangle containment" },
            { 103, "Special subset sums: optimum" },
            { 104, "Pandigital Fibonacci ends" },
            { 105, "Special subset sums: testing" },
            { 106, "Special subset sums: meta-testing" },
            { 107, "Minimal network" },
            { 108, "Diophantine reciprocals I" },
            { 109, "Darts" },
            { 110, "Diophantine reciprocals II" },
            { 111, "Primes with runs" },
            { 112, "Bouncy numbers" },
            { 113, "Non-bouncy numbers" },
            { 114, "Counting block combinations I" },
            { 115, "Counting block combinations II" },
            { 116, "Red, green or blue tiles" },
            { 117, "Red, green, and blue tiles" },
            { 118, "Pandigital prime sets" },
            { 119, "Digit power sum" },
            { 120, "Square remainders" },
            { 121, "Disc game prize fund" },
            { 122, "Efficient exponentiation" },
            { 123, "Prime square remainders" },
            { 124, "Ordered radicals" },
            { 125, "Palindromic sums" },
            { 126, "Cuboid layers" },
            { 127, "abc-hits" },
            { 128, "Hexagonal tile differences" },
            { 129, "Repunit divisibility" },
            { 130, "Composites with prime repunit property" },
            { 131, "Prime cube partnership" },
            { 132, "Large repunit factors" },
            { 133, "Repunit nonfactors" },
            { 134, "Prime pair connection" },
            { 135, "Same differences" },
            { 136, "Singleton difference" },
            { 137, "Fibonacci golden nuggets" },
            { 138, "Special isosceles triangles" },
            { 139, "Pythagorean tiles" },
            { 140, "Modified Fibonacci golden nuggets" },
            { 141, "Investigating progressive numbers, n, which are also square" },
            { 142, "Perfect Square Collection" },
            { 143, "Investigating the Torricelli point of a triangle" },
            { 144, "Investigating multiple reflections of a laser beam" },
            { 145, "How many reversible numbers are there below one-billion?" },
            { 146, "Investigating a Prime Pattern" },
            { 147, "Rectangles in cross-hatched grids" },
            { 148, "Exploring Pascal's triangle" },
            { 149, "Searching for a maximum-sum subsequence" },
            { 150, "Searching a triangular array for a sub-triangle having minimum-sum" },
            { 151, "Paper sheets of standard sizes: an expected-value problem" },
            { 152, "Writing 1/2 as a sum of inverse squares" },
            { 153, "Investigating Gaussian Integers" },
            { 154, "Exploring Pascal's pyramid" },
            { 155, "Counting Capacitor Circuits" },
            { 156, "Counting Digits" },
            { 157, "Solving the diophantine equation 1/a+1/b= p/10n" },
            { 158, "Exploring strings for which only one character comes lexicographically after its neighbour to the left" },
            { 159, "Digital root sums of factorisations" },
            { 160, "Factorial trailing digits" },
            { 161, "Triominoes" },
            { 162, "Hexadecimal numbers" },
            { 163, "Cross-hatched triangles" },
            { 164, "Numbers for which no three consecutive digits have a sum greater than a given value" },
            { 165, "Intersections" },
            { 166, "Criss Cross" },
            { 167, "Investigating Ulam sequences" },
            { 168, "Number Rotations" },
            { 169, "Exploring the number of different ways a number can be expressed as a sum of powers of 2" },
            { 170, "Find the largest 0 to 9 pandigital that can be formed by concatenating products" },
            { 171, "Finding numbers for which the sum of the squares of the digits is a square" },
            { 172, "Investigating numbers with few repeated digits" },
            { 173, "Using up to one million tiles how many different \"hollow\" square laminae can be formed?" },
            { 174, "Counting the number of \"hollow\" square laminae that can form one, two, three, ... distinct arrangements" },
            { 175, "Fractions involving the number of different ways a number can be expressed as a sum of powers of 2" },
            { 176, "Right-angled triangles that share a cathetus" },
            { 177, "Integer angled Quadrilaterals" },
            { 178, "Step Numbers" },
            { 179, "Consecutive positive divisors" },
            { 180, "Rational zeros of a function of three variables" },
            { 181, "Investigating in how many ways objects of two different colours can be grouped" },
            { 182, "RSA encryption" },
            { 183, "Maximum product of parts" },
            { 184, "Triangles containing the origin" },
            { 185, "Number Mind" },
            { 186, "Connectedness of a network" },
            { 187, "Semiprimes" },
            { 188, "The hyperexponentiation of a number" },
            { 189, "Tri-colouring a triangular grid" },
            { 190, "Maximising a weighted product" },
            { 191, "Prize Strings" },
            { 192, "Best Approximations" },
            { 193, "Squarefree Numbers" },
            { 194, "Coloured Configurations" },
            { 195, "Inscribed circles of triangles with one angle of 60 degrees" },
            { 196, "Prime triplets" },
            { 197, "Investigating the behaviour of a recursively defined sequence" },
            { 198, "Ambiguous Numbers" },
            { 199, "Iterative Circle Packing" },
            { 200, "Find the 200th prime-proof sqube containing the contiguous sub-string \"200\"" },
            { 201, "Subsets with a unique sum" },
            { 202, "Laserbeam" },
            { 203, "Squarefree Binomial Coefficients" },
            { 204, "Generalised Hamming Numbers" },
            { 205, "Dice Game" },
            { 206, "Concealed Square" },
            { 207, "Integer partition equations" },
            { 208, "Robot Walks" },
            { 209, "Circular Logic" },
            { 210, "Obtuse Angled Triangles" },
            { 211, "Divisor Square Sum" },
            { 212, "Combined Volume of Cuboids" },
            { 213, "Flea Circus" },
            { 214, "Totient Chains" },
            { 215, "Crack-free Walls" },
            { 216, "Investigating the primality of numbers of the form 2n2-1" },
            { 217, "Balanced Numbers" },
            { 218, "Perfect right-angled triangles" },
            { 219, "Skew-cost coding" },
            { 220, "Heighway Dragon" },
            { 221, "Alexandrian Integers" },
            { 222, "Sphere Packing" },
            { 223, "Almost right-angled triangles I" },
            { 224, "Almost right-angled triangles II" },
            { 225, "Tribonacci non-divisors" },
            { 226, "A Scoop of Blancmange" },
            { 227, "The Chase" },
            { 228, "Minkowski Sums" },
            { 229, "Four Representations using Squares" },
            { 230, "Fibonacci Words" },
            { 231, "The prime factorisation of binomial coefficients" },
            { 232, "The Race" },
            { 233, "Lattice points on a circle" },
            { 234, "Semidivisible numbers" },
            { 235, "An Arithmetic Geometric sequence" },
            { 236, "Luxury Hampers" },
            { 237, "Tours on a 4 x n playing board" },
            { 238, "Infinite string tour" },
            { 239, "Twenty-two Foolish Primes" },
            { 240, "Top Dice" },
            { 241, "Perfection Quotients" },
            { 242, "Odd Triplets" },
            { 243, "Resilience" },
            { 244, "Sliders" },
            { 245, "Coresilience" },
            { 246, "Tangents to an ellipse" },
            { 247, "Squares under a hyperbola" },
            { 248, "Numbers for which Euler’s totient function equals 13!" },
            { 249, "Prime Subset Sums" },
            { 250, "250250" },
            { 251, "Cardano Triplets" },
            { 252, "Convex Holes" },
            { 253, "Tidying up" },
            { 254, "Sums of Digit Factorials" },
            { 255, "Rounded Square Roots" },
            { 256, "Tatami-Free Rooms" },
            { 257, "Angular Bisectors" },
            { 258, "A lagged Fibonacci sequence" },
            { 259, "Reachable Numbers" },
            { 260, "Stone Game" },
            { 261, "Pivotal Square Sums" },
            { 262, "Mountain Range" },
            { 263, "An engineers' dream come true" },
            { 264, "Triangle Centres" },
            { 265, "Binary Circles" },
            { 266, "Pseudo Square Root" },
            { 267, "Billionaire" },
            { 268, "Counting numbers with at least four distinct prime factors less than 100" },
            { 269, "Polynomials with at least one integer root" },
            { 270, "Cutting Squares" },
            { 271, "Modular Cubes, part 1" },
            { 272, "Modular Cubes, part 2" },
            { 273, "Sum of Squares" },
            { 274, "Divisibility Multipliers" },
            { 275, "Balanced Sculptures" },
            { 276, "Primitive Triangles" },
            { 277, "A Modified Collatz sequence" },
            { 278, "Linear Combinations of Semiprimes" },
            { 279, "Triangles with integral sides and an integral angle" },
            { 280, "Ant and seeds" },
            { 281, "Pizza Toppings" },
            { 282, "The Ackermann function" },
            { 283, "Integer sided triangles for which the area/perimeter ratio is integral" },
            { 284, "Steady Squares" },
            { 285, "Pythagorean odds" },
            { 286, "Scoring probabilities" },
            { 287, "Quadtree encoding (a simple compression algorithm)" },
            { 288, "An enormous factorial" },
            { 289, "Eulerian Cycles" },
            { 290, "Digital Signature" },
            { 291, "Panaitopol Primes" },
            { 292, "Pythagorean Polygons" },
            { 293, "Pseudo-Fortunate Numbers" },
            { 294, "Sum of digits - experience #23" },
            { 295, "Lenticular holes" },
            { 296, "Angular Bisector and Tangent" },
            { 297, "Zeckendorf Representation" },
            { 298, "Selective Amnesia" },
            { 299, "Three similar triangles" },
            { 300, "Protein folding" },
            { 301, "Nim" },
            { 302, "Strong Achilles Numbers" },
            { 303, "Multiples with small digits" },
            { 304, "Primonacci" },
            { 305, "Reflexive Position" },
            { 306, "Paper-strip Game" },
            { 307, "Chip Defects" },
            { 308, "An amazing Prime-generating Automaton" },
            { 309, "Integer Ladders" },
            { 310, "Nim Square" },
            { 311, "Biclinic Integral Quadrilaterals" },
            { 312, "Cyclic paths on Sierpiński graphs" },
            { 313, "Sliding game" },
            { 314, "The Mouse on the Moon" },
            { 315, "Digital root clocks" },
            { 316, "Numbers in decimal expansions" },
            { 317, "Firecracker" },
            { 318, "2011 nines" },
            { 319, "Bounded Sequences" },
            { 320, "Factorials divisible by a huge integer" },
            { 321, "Swapping Counters" },
            { 322, "Binomial coefficients divisible by 10" },
            { 323, "Bitwise-OR operations on random integers" },
            { 324, "Building a tower" },
            { 325, "Stone Game II" },
            { 326, "Modulo Summations" },
            { 327, "Rooms of Doom" },
            { 328, "Lowest-cost Search" },
            { 329, "Prime Frog" },
            { 330, "Euler's Number" },
            { 331, "Cross flips" },
            { 332, "Spherical triangles" },
            { 333, "Special partitions" },
            { 334, "Spilling the beans" },
            { 335, "Gathering the beans" },
            { 336, "Maximix Arrangements" },
            { 337, "Totient Stairstep Sequences" },
            { 338, "Cutting Rectangular Grid Paper" },
            { 339, "Peredur fab Efrawg" },
            { 340, "Crazy Function" },
            { 341, "Golomb's self-describing sequence" },
            { 342, "The totient of a square is a cube" },
            { 343, "Fractional Sequences" },
            { 344, "Silver dollar game" },
            { 345, "Matrix Sum" },
            { 346, "Strong Repunits" },
            { 347, "Largest integer divisible by two primes" },
            { 348, "Sum of a square and a cube" },
            { 349, "Langton's ant" },
            { 350, "Constraining the least greatest and the greatest least" },
            { 351, "Hexagonal orchards" },
            { 352, "Blood tests" },
            { 353, "Risky moon" },
            { 354, "Distances in a bee's honeycomb" },
            { 355, "Maximal coprime subset" },
            { 356, "Largest roots of cubic polynomials" },
            { 357, "Prime generating integers" },
            { 358, "Cyclic numbers" },
            { 359, "Hilbert's New Hotel" },
            { 360, "Scary Sphere" },
            { 361, "Subsequence of Thue-Morse sequence" },
            { 362, "Squarefree factors" },
            { 363, "Bézier Curves" },
            { 364, "Comfortable distance" },
            { 365, "A huge binomial coefficient" },
            { 366, "Stone Game III" },
            { 367, "Bozo sort" },
            { 368, "A Kempner-like series" },
            { 369, "Badugi" },
            { 370, "Geometric triangles" },
            { 371, "Licence plates" },
            { 372, "Pencils of rays" },
            { 373, "Circumscribed Circles" },
            { 374, "Maximum Integer Partition Product" },
            { 375, "Minimum of subsequences" },
            { 376, "Nontransitive sets of dice" },
            { 377, "Sum of digits, experience 13" },
            { 378, "Triangle Triples" },
            { 379, "Least common multiple count" },
            { 380, "Amazing Mazes!" },
            { 381, "(prime-k) factorial" },
            { 382, "Generating polygons" },
            { 383, "Divisibility comparison between factorials" },
            { 384, "Rudin-Shapiro sequence" },
            { 385, "Ellipses inside triangles" },
            { 386, "Maximum length of an antichain" },
            { 387, "Harshad Numbers" },
            { 388, "Distinct Lines" },
            { 389, "Platonic Dice" },
            { 390, "Triangles with non rational sides and integral area" },
            { 391, "Hopping Game" },
            { 392, "Enmeshed unit circle" },
            { 393, "Migrating ants" },
            { 394, "Eating pie" },
            { 395, "Pythagorean tree" },
            { 396, "Weak Goodstein sequence" },
            { 397, "Triangle on parabola" },
            { 398, "Cutting rope" },
            { 399, "Squarefree Fibonacci Numbers" },
            { 400, "Fibonacci tree game" },
            { 401, "Sum of squares of divisors" },
            { 402, "Integer-valued polynomials" },
            { 403, "Lattice points enclosed by parabola and line" },
            { 404, "Crisscross Ellipses" },
            { 405, "A rectangular tiling" },
            { 406, "Guessing Game" },
            { 407, "Idempotents" },
            { 408, "Admissible paths through a grid" },
            { 409, "Nim Extreme" },
            { 410, "Circle and tangent line" },
            { 411, "Uphill paths" },
            { 412, "Gnomon numbering" },
            { 413, "One-child Numbers" },
            { 414, "Kaprekar constant" },
            { 415, "Titanic sets" },
            { 416, "A frog's trip" },
            { 417, "Reciprocal cycles II" },
            { 418, "Factorisation triples" },
            { 419, "Look and say sequence" },
            { 420, "2x2 positive integer matrix" },
            { 421, "Prime factors of n15+1" },
            { 422, "Sequence of points on a hyperbola" },
            { 423, "Consecutive die throws" },
            { 424, "Kakuro" },
            { 425, "Prime connection" },
            { 426, "Box-ball system" },
            { 427, "n-sequences" },
            { 428, "Necklace of circles" },
            { 429, "Sum of squares of unitary divisors" },
            { 430, "Range flips" },
            { 431, "Square Space Silo" },
            { 432, "Totient sum" },
            { 433, "Steps in Euclid's algorithm" },
            { 434, "Rigid graphs" },
            { 435, "Polynomials of Fibonacci numbers" },
            { 436, "Unfair wager" },
            { 437, "Fibonacci primitive roots" },
            { 438, "Integer part of polynomial equation's solutions" },
            { 439, "Sum of sum of divisors" },
            { 440, "GCD and Tiling" },
            { 441, "The inverse summation of coprime couples" },
            { 442, "Eleven-free integers" },
            { 443, "GCD sequence" },
            { 444, "The Roundtable Lottery" },
            { 445, "Retractions A" },
            { 446, "Retractions B" },
            { 447, "Retractions C" },
            { 448, "Average least common multiple" },
            { 449, "Chocolate covered candy" },
            { 450, "Hypocycloid and Lattice points" },
            { 451, "Modular inverses" },
            { 452, "Long Products" },
            { 453, "Lattice Quadrilaterals" },
            { 454, "Diophantine reciprocals III" },
            { 455, "Powers With Trailing Digits" },
            { 456, "Triangles containing the origin II" },
            { 457, "A polynomial modulo the square of a prime" },
            { 458, "Permutations of Project" },
            { 459, "Flipping game" },
            { 460, "An ant on the move" },
            { 461, "Almost Pi" },
            { 462, "Permutation of 3-smooth numbers" },
            { 463, "A weird recurrence relation" },
            { 464, "Möbius function and intervals" },
            { 465, "Polar polygons" },
            { 466, "Distinct terms in a multiplication table" },
            { 467, "Superinteger" },
            { 468, "Smooth divisors of binomial coefficients" },
            { 469, "Empty chairs" },
            { 470, "Super Ramvok" },
            { 471, "Triangle inscribed in ellipse" },
            { 472, "Comfortable Distance II" },
            { 473, "Phigital number base" },
            { 474, "Last digits of divisors" },
            { 475, "Music festival" },
            { 476, "Circle Packing II" },
            { 477, "Number Sequence Game" },
            { 478, "Mixtures" },
            { 479, "Roots on the Rise" },
            { 480, "The Last Question" },
            { 481, "Chef Showdown" },
            { 482, "The incenter of a triangle" },
            { 483, "Repeated permutation" },
            { 484, "Arithmetic Derivative" },
            { 485, "Maximum number of divisors" },
            { 486, "Palindrome-containing strings" },
            { 487, "Sums of power sums" },
            { 488, "Unbalanced Nim" },
            { 489, "Common factors between two sequences" },
            { 490, "Jumping frog" },
            { 491, "Double pandigital number divisible by 11" },
            { 492, "Exploding sequence" },
            { 493, "Under The Rainbow" },
            { 494, "Collatz prefix families" },
            { 495, "Writing n as the product of k distinct positive integers" },
            { 496, "Incenter and circumcenter of triangle" },
            { 497, "Drunken Tower of Hanoi" },
            { 498, "Remainder of polynomial division" },
            { 499, "St. Petersburg Lottery" },
            { 500, "Problem 500!!!" },
            { 501, "Eight Divisors" },
            { 502, "Counting Castles" },
            { 503, "Compromise or persist" },
            { 504, "Square on the Inside" },
            { 505, "Bidirectional Recurrence" },
            { 506, "Clock sequence" },
            { 507, "Shortest Lattice Vector" },
            { 508, "Integers in base i-1" },
            { 509, "Divisor Nim" },
            { 510, "Tangent Circles" },
            { 511, "Sequences with nice divisibility properties" },
            { 512, "Sums of totients of powers" },
            { 513, "Integral median" },
            { 514, "Geoboard Shapes" },
            { 515, "Dissonant Numbers" },
            { 516, "5-smooth totients" },
            { 517, "A real recursion" },
            { 518, "Prime triples and geometric sequences" },
            { 519, "Tricolored Coin Fountains" },
            { 520, "Simbers" },
            { 521, "Smallest prime factor" },
            { 522, "Hilbert's Blackout" },
            { 523, "First Sort I" },
            { 524, "First Sort II" },
            { 525, "Rolling Ellipse" },
            { 526, "Largest prime factors of consecutive numbers" },
            { 527, "Randomized Binary Search" },
            { 528, "Constrained Sums" },
            { 529, "10-substrings" },
            { 530, "GCD of Divisors" },
            { 531, "Chinese leftovers" },
            { 532, "Nanobots on Geodesics" },
            { 533, "Minimum values of the Carmichael function" },
            { 534, "Weak Queens" },
            { 535, "Fractal Sequence" },
            { 536, "Modulo power identity" },
            { 537, "Counting tuples" },
            { 538, "Maximum quadrilaterals" },
            { 539, "Odd elimination" },
            { 540, "Counting primitive Pythagorean triples" },
            { 541, "Divisibility of Harmonic Number Denominators" },
            { 542, "Geometric Progression with Maximum Sum" },
            { 543, "Prime-Sum Numbers" },
            { 544, "Chromatic Conundrum" },
            { 545, "Faulhaber's Formulas" },
            { 546, "The Floor's Revenge" },
            { 547, "Distance of random points within hollow square laminae" },
            { 548, "Gozinta Chains" },
            { 549, "Divisibility of factorials" },
            { 550, "Divisor game" },
            { 551, "Sum of digits sequence" },
            { 552, "Chinese leftovers II" },
            { 553, "Power sets of power sets" },
            { 554, "Centaurs on a chess board" },
            { 555, "McCarthy 91 function" },
            { 556, "Squarefree Gaussian Integers" },
            { 557, "Cutting triangles" },
            { 558, "Irrational base" },
            { 559, "Permuted Matrices" },
            { 560, "Coprime Nim" },
            { 561, "Divisor Pairs" },
            { 562, "Maximal perimeter" },
            { 563, "Robot Welders" },
            { 564, "Maximal polygons" },
            { 565, "Divisibility of sum of divisors" },
            { 566, "Cake Icing Puzzle" },
            { 567, "Reciprocal games I" },
            { 568, "Reciprocal games II" },
            { 569, "Prime Mountain Range" },
            { 570, "Snowflakes" },
            { 571, "Super Pandigital Numbers" },
            { 572, "Idempotent matrices" },
            { 573, "Unfair race" },
            { 574, "Verifying Primes" },
            { 575, "Wandering Robots" },
            { 576, "Irrational jumps" },
            { 577, "Counting hexagons" },
            { 578, "Integers with decreasing prime powers" },
            { 579, "Lattice points in lattice cubes" },
            { 580, "Squarefree Hilbert numbers" },
            { 581, "47-smooth triangular numbers" },
            { 582, "Nearly isosceles 120 degree triangles" },
            { 583, "Heron Envelopes" },
            { 584, "Birthday Problem Revisited" },
            { 585, "Nested square roots" },
            { 586, "Binary Quadratic Form" },
            { 587, "Concave triangle" },
            { 588, "Quintinomial coefficients" },
            { 589, "Poohsticks Marathon" },
            { 590, "Sets with a given Least Common Multiple" },
            { 591, "Best Approximations by Quadratic Integers" },
            { 592, "Factorial trailing digits 2" },
            { 593, "Fleeting Medians" },
            { 594, "Rhombus Tilings" },
            { 595, "Incremental Random Sort" },
            { 596, "Number of lattice points in a hyperball" },
            { 597, "Torpids" },
            { 598, "Split Divisibilities" },
    })
{
}

// vim:set sw=4 ts=4 et:
